
name: Download RyukGram DEB

on:
  workflow_dispatch:

env:
  UPSTREAM_REPO: faroukbmiled/RyukGram


jobs:

  build:

    runs-on: macos-latest

    steps:

    - name: Install dpkg
      run: |
        brew install dpkg


    - name: Get latest release
      id: release
      run: |
        TAG=$(gh release view \
        --repo "$UPSTREAM_REPO" \
        --json tagName \
        -q .tagName)

        echo "TAG=$TAG" >> $GITHUB_ENV

        echo "Release:"
        echo $TAG



    - name: Download DEB
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -e

        mkdir -p output


        gh release download "$TAG" \
          --repo "$UPSTREAM_REPO" \
          --dir output \
          --pattern "*rootless.deb"



        echo "Downloaded:"
        ls -lh output



    - name: Verify DEB
      run: |
        set -e


        DEB=$(find output -name "*.deb" | head -1)


        if [ -z "$DEB" ]; then
          echo "No deb found"
          exit 1
        fi


        echo "Checking:"
        echo "$DEB"


        dpkg-deb -I "$DEB"



    - name: Upload DEB

      uses: actions/upload-artifact@v4

      with:

        name: RyukGram-DEB

        path: output/*.deb
